### ISSUE TITLE
jamText.setLayerText(layerText) can't set "defaultStyle"

### ISSUE THREAD

**Issue by Vielmond** [tonton-pixel/JSON-Photoshop-Scripting#1]
It's currently impossible to set a `defaultStyle` using the `jamText.setLayerText()` method on Photoshop CS6. `defaultStyle` is part of `paragraphStyle`:

	{
		"layerText": {
			"paragraphStyleRange": [
				{
					"paragraphStyle": {
						"defaultStyle": {
							 _settings_
						 }
					}
				},
			]
		},
	};

It seems to be the object storing Paragraph Styles settings applied to the text, and it's lost upon modifying `paragraphStyleRange`.

### Steps to reproduce the issue:

**On Photoshop**

1. Create a new document and add a text layer.
2. Write something and select the text.
3. Change the text size to something other than the default. Example: 24pt.
4. Go to Window > Paragraph Styles to open the panel, then click on "Create a New Paragraph Style". The new style will be already applied.

**Script**

1. After setting the Paragraph Style I used the following script in ExtendScript Toolkit to keep track of what was happening. It's pretty simple, getting the textlayer then setting it without changing anything:

		//@include "jamEngine.jsxinc"
		//@include "jamHelpers.jsxinc"
		//@include "jamJSON.jsxinc"
		//@include "jamText.jsxinc"
		//@include "jamUtils.jsxinc"
		//
		var textLayerObj = jamText.getLayerText();
		$.writeln(":: Original textLayer");
		$.writeln( jamJSON.stringify ( textLayerObj, "\t" ) );
		$.writeln("\n");
		//
		jamText.setLayerText(textLayerObj);
		//
		var textLayerObjUpdated = jamText.getLayerText();
		$.writeln("::: New textLayer");
		$.writeln( jamJSON.stringify ( textLayerObjUpdated, "\t" ) );
		$.writeln("\n"); 

**Result**
The modified text layer will be almost identical to the original version. It'll have the paragraph style on Photoshop > Paragraph Styles, but marked as "overriden" now. The actual paragraph style in effect will be the _Basic Paragraph_.

Among other settings, `defaultStyle` will be present in the original object, but not in the get output after using `jamText.setLayerText(textLayerObj);` . While the other missing properties aren't that important, Paragraph Styles are a central feature of text layers.

Maybe I'm just doing it wrong since I'm not the most skilled script writer, but I suspect it may be an AM limitation. It was upon failing to set it using plain AM that I set out to find a library to help and ended finding jam—awesome work by the way!—and the trouble I'm having setting it with jam strikes me as too big of a coincidence.

**Comment by tonton-pixel** [comment]
Unfortunately, I stopped working on this project a few years ago...

Actually, I had to dig out from an older computer some replies I made to users who wrote to me using my previous web site contact form. Here are a few excerpts related to character and paragraph styles:

> Thanks also for recently mentioning my jamText library on Adobe's forum. Unfortunately, it will probably never support recent features such as character and paragraph styles, since I am stuck on CS4 forever (no way to update my Basic Creative Suite to CS6 any more, and absolutely out of the question for a hobbyist like me to use this Adobe "cloudy" ripoff anyway).

> The jamText module is probably only useful up to Photoshop CS4, since it doesn't deal with text properties introduced later on. I kind of remember that many scripts ceased to function in CS6 (not only the ones written using my library) when support for paragraph styles and character styles was added, and that scaling of text has always been a big headache for developers for a long time.

> Unfortunately, I'm afraid I won't be able to help you in any way for recent versions of Photoshop. I am actually stuck forever in CS4, since Adobe doesn't allow me to upgrade my Basic Creative Suite CS4 (Photoshop, Illustrator, inDesign) any more since last year...
> It seems that programming getting/setting text is even more difficult that what it used to be since the introduction of character and paragraph stylesheets in CS6, IIRC. And apparently new bugs have even been introduced in more recent versions, regarding font size, for instance.

Thanks for your detailed report and your kind words of appreciation anyway.
Good luck!
